#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Format Rust code
cargo fmt -- --check

# Run Clippy (with allowed warnings)
cargo clippy -- \
    -A dead_code \
    -A unused_variables \
    -A unused_imports \
    -D warnings

# Check formatting of other files
pnpm fmt:check
