#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Build the project
cargo build

# Run clippy with allowed warnings
cargo clippy -- \
    -A dead_code \
    -A unused_variables \
    -A unused_imports \
    -D warnings

# TODO: Run tests if necessary
# cargo test
